// Comprehensive Dummy Data for View Only Mode

export const dummyStudents = [
  {
    id: '1',
    name: 'Aarav Kumar',
    roll: '1',
    class: '10',
    section: 'A',
    email: 'aarav@school.com',
    phone: '9876543210',
    address: '123 Main St, City',
    attendance: '92%',
    performance: { hindi: 88, english: 85, math: 92, science: 90, social: 87 },
  },
  {
    id: '2',
    name: 'Diya Sharma',
    roll: '2',
    class: '10',
    section: 'A',
    email: 'diya@school.com',
    phone: '9876543211',
    address: '456 Oak Ave, City',
    attendance: '95%',
    performance: { hindi: 91, english: 89, math: 94, science: 92, social: 90 },
  },
  {
    id: '3',
    name: 'Arjun Patel',
    roll: '3',
    class: '10',
    section: 'A',
    email: 'arjun@school.com',
    phone: '9876543212',
    address: '789 Pine Rd, City',
    attendance: '88%',
    performance: { hindi: 85, english: 82, math: 88, science: 86, social: 84 },
  },
  {
    id: '4',
    name: 'Ananya Singh',
    roll: '4',
    class: '10',
    section: 'B',
    email: 'ananya@school.com',
    phone: '9876543213',
    address: '321 Elm St, City',
    attendance: '90%',
    performance: { hindi: 89, english: 87, math: 91, science: 89, social: 88 },
  },
  {
    id: '5',
    name: 'Ishaan Verma',
    roll: '5',
    class: '9',
    section: 'A',
    email: 'ishaan@school.com',
    phone: '9876543214',
    address: '654 Maple Dr, City',
    attendance: '93%',
    performance: { hindi: 86, english: 84, math: 89, science: 87, social: 85 },
  },
]

export const dummyTeachers = [
  {
    id: '1',
    name: 'Ms. Priya Sharma',
    subjects: 'Mathematics',
    classes: '9A, 10A, 10B',
    email: 'priya@school.com',
    phone: '9876543220',
    experience: '8 years',
  },
  {
    id: '2',
    name: 'Mr. Rajesh Kumar',
    subjects: 'English',
    classes: '9B, 10A',
    email: 'rajesh@school.com',
    phone: '9876543221',
    experience: '12 years',
  },
  {
    id: '3',
    name: 'Dr. Anjali Verma',
    subjects: 'Science',
    classes: '9A, 10B',
    email: 'anjali@school.com',
    phone: '9876543222',
    experience: '10 years',
  },
  {
    id: '4',
    name: 'Mr. Vikram Singh',
    subjects: 'Social Studies',
    classes: '9A, 9B, 10A',
    email: 'vikram@school.com',
    phone: '9876543223',
    experience: '6 years',
  },
]

export const dummyFeeRequests = [
  {
    id: '1',
    studentId: '1',
    studentName: 'Aarav Kumar',
    class: '10',
    section: 'A',
    type: 'fee_increase',
    amount: 500,
    reason: 'Lab facilities upgrade',
    date: '2026-01-15',
    status: 'pending',
  },
  {
    id: '2',
    studentId: '2',
    studentName: 'Diya Sharma',
    class: '10',
    section: 'A',
    type: 'discount_request',
    amount: 1000,
    reason: 'Financial hardship',
    date: '2026-01-10',
    status: 'approved',
  },
  {
    id: '3',
    studentId: '3',
    studentName: 'Arjun Patel',
    class: '10',
    section: 'A',
    type: 'fee_waiver',
    amount: 5000,
    reason: 'Merit scholarship',
    date: '2026-01-18',
    status: 'pending',
  },
]

export const dummyStudentClasses = [
  {
    name: 'Mathematics - Class 10A',
    teacher: 'Ms. Priya Sharma',
    time: 'Monday-Friday, 9:00-10:00 AM',
    room: '201',
    marks: 92,
  },
  {
    name: 'English - Class 10A',
    teacher: 'Mr. Rajesh Kumar',
    time: 'Monday-Friday, 10:15-11:15 AM',
    room: '203',
    marks: 85,
  },
  {
    name: 'Science - Class 10A',
    teacher: 'Dr. Anjali Verma',
    time: 'Monday-Friday, 2:00-3:30 PM',
    room: '205',
    marks: 90,
  },
  {
    name: 'Social Studies - Class 10A',
    teacher: 'Mr. Vikram Singh',
    time: 'Tuesday-Saturday, 11:30 AM-12:30 PM',
    room: '207',
    marks: 87,
  },
]

export const dummyStudentPerformance = [
  { month: 'Aug', math: 85, english: 80, science: 82, social: 78 },
  { month: 'Sep', math: 87, english: 82, science: 85, social: 81 },
  { month: 'Oct', math: 89, english: 84, science: 87, social: 83 },
  { month: 'Nov', math: 91, english: 86, science: 89, social: 85 },
  { month: 'Dec', math: 92, english: 88, science: 91, social: 87 },
  { month: 'Jan', math: 94, english: 89, science: 92, social: 89 },
]
